#!/bin/bash /etc/rc.common
# Copyright (C) 2010-2011 OpenWrt.org

START=50

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start_instance() {
	local section="$1"
	local enabled
	local port

	config_get_bool enabled "$section" 'enabled' 0
	config_get port "$section" 'port' 1026

	[ $enabled -gt 0 ] || return 1

	PHP_FCGI_CHILDREN=1 \
	php-fcgi-daemon $port &
}

start() {
	config_load 'php5-fastcgi'
	config_foreach start_instance 'php5-fastcgi'
}

stop() {
	killall -9 php-fcgi-daemon
	killall -9 php-fcgi
}
